services:
  web:
    image: wp-host:1.0.0
    build: ./
    ports:
      - 80:80
    volumes:
      - ./wp-app:/wp-app
      - web-user-volume:/home/wp
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql-mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
  web-user-volume:
